# action.yml
name: cosign-action
description: 'Install Cosign and put it on your path'
branding:
  icon: 'package'
  color: 'blue'

inputs:
  version:
    description: 'Cosign release version to use in the actions'
    default: 'latest'
    required: false
  args:
    description: 'Arguments to pass to cosign'
    required: false
  workdir:
    description: 'Working directory (below repository root)'
    default: '.'
    required: false
  install-only:
    description: 'Just install GoReleaser'
    default: 'false'
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'
