name: test-cosign

on:
  push:
    branches:
      - 'v2'
  pull_request:
    branches:
      - 'v2'

jobs:
  install-only:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        version:
          - latest
          - '~> 1.3'
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: cosign
        uses: ./
        with:
          version: ${{ matrix.version }}
          install-only: true
      - name: Check
        run: |
          cosign version
      - name: Check root directory
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          if [[ $(git diff --stat) != '' ]]; then
            echo 'should be clean'
            exit 1
          else
            exit 0
          fi

  verify-sig:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        version:
          - latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: cosign
        uses: ./
        with:
          version: ${{ matrix.version }}
          args: verify --key https://raw.githubusercontent.com/sigstore/cosign/main/release/release-cosign.pub gcr.io/projectsigstore/cosign:v1.4.0
