name: test

on:
  push:
    branches:
      - 'v2'
  pull_request:
    branches:
      - 'v2'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Validate
        uses: docker/bake-action@v1
        with:
          targets: validate
      - name: Test
        uses: docker/bake-action@v1
        with:
          targets: test
      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          file: ./coverage/clover.xml
